---
  - name: ensure S3 bucket
    s3_bucket:
      name: "{{ s3_bucket_name }}"
      state: present
      aws_region: "{{ aws_region }}"
      tags:
        Application: "{{ app_name }}"
        Environment: "{{ env_name }}"
        Project: "{{ proj_name }}"
        Tier: "storage"
