---
  - name: ensure IAM account for access to Route53 zone
    iam:
      name: "{{ r53_zone_domain }}-lego-user"
      iam_type: user
      state: present

  - name: ensure IAM policy is attached to the user account
    iam_policy:
      iam_type: user
      iam_name: "{{ r53_zone_domain }}-lego-user"
      policy_name: "{{ r53_zone_domain }}-lego-policy"
      policy_json: "{{ lookup( 'template', 'lego_user_policy.json.j2') | to_json }}"
      state: present
